const SOCKET_API_ROUTE_ECHO = 'api/echo';
const SOCKET_API_ROUTE_ENV = 'api/env'; // TODO: Rename to fetchEnv
const SOCKET_API_ROUTE_DEBUG_ERROR = 'api/debug:error';
const SOCKET_API_ROUTE_PING = 'api/host:ping'; // ping is a reserved Socket.io word
const SOCKET_API_ROUTE_FILESYSTEM = 'api/fileSystem';
const SOCKET_API_ROUTE_FETCH_SYSTEM_TIME = 'api/fetch-system-time';
const SOCKET_API_ROUTE_FETCH_X_APPS = 'api/fetch-apps';
const SOCKET_API_ROUTE_FETCH_X_APP_CATEGORIES = 'api/fetch-app-categories';
const SOCKET_API_ROUTE_SYSTEM_COMMAND = 'api/system-command';
const SOCKET_API_ROUTE_FETCH_SYS_INFO = 'api/fetch-sys-info';
const SOCKET_API_ROUTE_FETCH_SYS_INFO_MODES = 'api/fetch-sys-info-modes';
const SOCKET_API_ROUTE_PORT_AUDIO_FETCH_DEVICES = 'api/port-audio:fetch-devices';
const SOCKET_API_ROUTE_PORT_AUDIO_FETCH_HOST_APIS = 'api/port-audio:fetch-host-apis';

// TODO: Rename to SOCKET_API_ROUTE_FETCH_WALLPAPER_PATHS
const SOCKET_API_ROUTE_WALLPAPERS_FETCH_WALLPAPER_PATHS = '/api/wallpapers:fetch-wallpaper-paths';

// P2P
const SOCKET_API_ROUTE_FETCH_SOCKET_IDS = 'api/fetch-peer-ids';
const SOCKET_API_ROUTE_SEND_SOCKET_PEER_DATA = 'api/send-peer-message';

// Socket channels
const SOCKET_API_ROUTE_CREATE_XTERM_SOCKET_CHANNEL = 'api/create-xterm-socket-channel';

const SOCKET_API_ROUTE_REQUEST_DISCONNECT = 'api/request-disconnect';

module.exports = {
  SOCKET_API_ROUTE_ECHO,
  SOCKET_API_ROUTE_ENV,
  SOCKET_API_ROUTE_DEBUG_ERROR,
  SOCKET_API_ROUTE_PING,
  SOCKET_API_ROUTE_FILESYSTEM,
  SOCKET_API_ROUTE_FETCH_SYSTEM_TIME,
  SOCKET_API_ROUTE_FETCH_X_APPS,
  SOCKET_API_ROUTE_FETCH_X_APP_CATEGORIES,
  SOCKET_API_ROUTE_SYSTEM_COMMAND,
  SOCKET_API_ROUTE_FETCH_SYS_INFO,
  SOCKET_API_ROUTE_FETCH_SYS_INFO_MODES,
  SOCKET_API_ROUTE_PORT_AUDIO_FETCH_DEVICES,
  SOCKET_API_ROUTE_PORT_AUDIO_FETCH_HOST_APIS,
  SOCKET_API_ROUTE_WALLPAPERS_FETCH_WALLPAPER_PATHS,

  // P2P
  SOCKET_API_ROUTE_FETCH_SOCKET_IDS,
  SOCKET_API_ROUTE_SEND_SOCKET_PEER_DATA,

  // Socket channels
  SOCKET_API_ROUTE_CREATE_XTERM_SOCKET_CHANNEL,

  SOCKET_API_ROUTE_REQUEST_DISCONNECT
};