const SOCKET_API_ROUTE_REQUEST_DISCONNECT = 'request-disconnect';
const SOCKET_API_ROUTE_ECHO = 'echo';
const SOCKET_API_ROUTE_DEBUG_ERROR = 'debug:error';
const SOCKET_API_ROUTE_PING = 'host:ping'; // ping is a reserved Socket.io word
const SOCKET_API_ROUTE_FILESYSTEM = 'fileSystem';
const SOCKET_API_ROUTE_FETCH_SYSTEM_TIME = 'fetch-system-time';
const SOCKET_API_ROUTE_FETCH_X_APPS = 'fetch-apps';
const SOCKET_API_ROUTE_FETCH_X_APP_CATEGORIES = 'fetch-app-categories';
const SOCKET_API_ROUTE_SYSTEM_COMMAND = 'system-command';
const SOCKET_API_ROUTE_FETCH_SYS_INFO = 'fetch-sys-info';
const SOCKET_API_ROUTE_FETCH_SYS_INFO_MODES = 'fetch-sys-info-modes';
const SOCKET_API_ROUTE_PORT_AUDIO_FETCH_DEVICES = 'port-audio:fetch-devices';
const SOCKET_API_ROUTE_PORT_AUDIO_FETCH_HOST_APIS = 'port-audio:fetch-host-apis';
// TODO: Rename to SOCKET_API_ROUTE_FETCH_WALLPAPER_PATHS
const SOCKET_API_ROUTE_WALLPAPERS_FETCH_WALLPAPER_PATHS = 'wallpapers:fetch-wallpaper-paths';

module.exports = {
  SOCKET_API_ROUTE_REQUEST_DISCONNECT,
  SOCKET_API_ROUTE_ECHO,
  SOCKET_API_ROUTE_DEBUG_ERROR,
  SOCKET_API_ROUTE_PING,
  SOCKET_API_ROUTE_FILESYSTEM,
  SOCKET_API_ROUTE_FETCH_SYSTEM_TIME,
  SOCKET_API_ROUTE_FETCH_X_APPS,
  SOCKET_API_ROUTE_FETCH_X_APP_CATEGORIES,
  SOCKET_API_ROUTE_SYSTEM_COMMAND,
  SOCKET_API_ROUTE_FETCH_SYS_INFO,
  SOCKET_API_ROUTE_FETCH_SYS_INFO_MODES,
  SOCKET_API_ROUTE_PORT_AUDIO_FETCH_DEVICES,
  SOCKET_API_ROUTE_PORT_AUDIO_FETCH_HOST_APIS,
  SOCKET_API_ROUTE_WALLPAPERS_FETCH_WALLPAPER_PATHS
};