import {
  SOCKET_API_EVT_PEER_ID_CONNECT,
  SOCKET_API_EVT_PEER_ID_DISCONNECT,
  SOCKET_API_EVT_PEER_DATA
} from '../_bind/_origin/_backend/_backend_socketAPIEvents';

export {
  SOCKET_API_EVT_PEER_ID_CONNECT,
  SOCKET_API_EVT_PEER_ID_DISCONNECT,
  SOCKET_API_EVT_PEER_DATA
};
