import Window, {
  EVT_MOUNT,
  EVT_BEFORE_UNMOUNT,
  EVT_BEFORE_CLOSE,
  EVT_BEFORE_FOCUS,
  EVT_RESIZE
} from './Window';

export default Window;
export {
  EVT_MOUNT,
  EVT_BEFORE_UNMOUNT,
  EVT_BEFORE_CLOSE,
  EVT_BEFORE_FOCUS,
  EVT_RESIZE
};